services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/attendance_db'
      - 'SPRING_DATASOURCE_USERNAME=sa'
      - 'SPRING_DATASOURCE_PASSWORD=password'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=attendance_db'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=sa'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sa -d attendance_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: