version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"  # Adjust this host port if needed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
