# curl -X POST https://pt-backend-42d98685b856.herokuapp.com/api/auth/login
#-H "Content-Type: application/json"
#-d '{
#    "username": "admin",
#    "password": "admin123"
#}'
POST https://pt-backend-42d98685b856.herokuapp.com/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}
https://pt-backend-42d98685b856.herokuapp.com/api/qr/check-in/3

###

# curl -X POST
#  'https://pt-backend-42d98685b856.herokuapp.com/api/qr/check-in/3'
#  -H 'Content-Type: application/json'
#  -u 'member:member123'
#  -d '{"qrCode": "GYM_LOCATION_001"}'
POST https://pt-backend-42d98685b856.herokuapp.com/api/qr/check-in/3
Authorization: Basic member member123
Content-Type: application/json

{
  "qrCode": "GYM_LOCATION_001"
}

###

# curl -v -X POST
#  'https://pt-backend-42d98685b856.herokuapp.com/api/qr/check-in/3'
#  -H 'Content-Type: application/json'
#  -u 'member:member123'
#  -d '{"qrCode": "GYM_LOCATION_001"}'
POST https://pt-backend-42d98685b856.herokuapp.com/api/qr/check-in/3
Authorization: Basic member member123
Content-Type: application/json

{
  "qrCode": "GYM_LOCATION_001"
}

###

# curl -v -X POST
#  'https://pt-backend-42d98685b856.herokuapp.com/api/auth/login'
#  -H 'Content-Type: application/json'
#  -d '{"username": "member", "password": "member123"}'
POST https://pt-backend-42d98685b856.herokuapp.com/api/auth/login
Content-Type: application/json

{
  "username": "member",
  "password": "member123"
}

###

# curl -v -X POST
#  'https://pt-backend-42d98685b856.herokuapp.com/api/qr/check-in/3'
#  -H 'Content-Type: application/json'
#  -H 'Cookie: JSESSIONID=your_session_id_from_login'
#  -d '{"qrCode": "GYM_LOCATION_001"}'
POST https://pt-backend-42d98685b856.herokuapp.com/api/qr/check-in/3
Cookie: JSESSIONID=your_session_id_from_login
Content-Type: application/json

{
  "qrCode": "GYM_LOCATION_001"
}

###

