# curl -X POST https://pt-backend-42d98685b856.herokuapp.com/api/auth/login
#-H "Content-Type: application/json"
#-d '{
#    "username": "admin",
#    "password": "admin123"
#}'
POST https://pt-backend-42d98685b856.herokuapp.com/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

https://pt-backend-42d98685b856.herokuapp.com/api/auth/login