# curl -X POST http://localhost:8080/api/auth/login
#-H "Content-Type: application/json"
#-d '{
#    "username": "testuser",
#    "password": "password123"
#}'
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###

# curl -X POST http://localhost:8080/api/auth/login
#-H "Content-Type: application/json"
#-H "Origin: http://127.0.0.1:5500"
#-H "Access-Control-Request-Method: POST"
#-d '{
#    "username": "test@user",
#    "password": "pass@123"
#}'
POST http://localhost:8080/api/auth/login
Origin: http://127.0.0.1:5500
Access-Control-Request-Method: POST
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}

###



# curl -X POST http://localhost:8080/api/auth/login
#-H "Content-Type: application/json"
#-H "Origin: http://127.0.0.1:5500"
#-H "Access-Control-Request-Method: POST"
#-H "Access-Control-Request-Headers: content-type"
#-d '{
#    "username": "testuser",
#    "password": "password123"
#}'
POST http://localhost:8080/api/auth/login
Origin: http://127.0.0.1:5500
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Content-Type: application/json

{
  "username": "member",
  "password": "member123"
}

###

